BASH SCRIPT [0-transfer_file] - Script that transfers a file from our client to a server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -17,3 +17,12 @@ PATH_TO_SSH_KEY=$4
 # disable strict hostkey checking when using scp
 
 scp -o "StrictHostKeyChecking=no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILES" "$USERNAME@IP:~/"
+
+# Checking for success or failure
+
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER SUCCESSFUL"
+else
+	echo "FLE TRANSFER FAILED"
+fi
